<grid>:
	fname: fname
	lname:lname
	email: email

	GridLayout:
		cols:1
		size: root.width-200, root.height-200
		pos: 100, 100
		
		GridLayout:
			cols:2

			Label:
				text: "First Name: "
			TextInput:
				id: fname
				multiline:False
			Label:
				text: "Last Name: "
			TextInput:
				id: lname
				multiline: False
		
			Label:
				text: "Email: "
			TextInput:
				id: email
				multiline:False

		Button:
			text:"Submit"
			on_press: root.btnpress()

			